version: "2"
services:
  app:
    image: reminisceme/app:latest
    env_file: ./env/prod.sh
    restart: on-failure:5

  nginx:
    build: nginx/
    ports:
      - 80:80
      - 443:443
    restart: on-failure:5

  game-creator:
    image: reminisceme/game-creator:latest
    cap_drop:
      - CHOWN
      - MKNOD
      - DAC_OVERRIDE
      - FSETID
      - FOWNER
      - SYS_CHROOT
    restart: on-failure:5

  mongo:
    image: mongo:3.2.4
    volumes_from:
      - data
    cap_drop:
      - DAC_OVERRIDE
      - FSETID
      - FOWNER
      - SYS_CHROOT
    restart: on-failure:5

  data:
    image: cogniteev/echo
    volumes:
      - /var/lib/mongo/data/db:/data/db
      - /misc:/misc
    cap_drop:
      - CHOWN
      - DAC_OVERRIDE
      - FSETID
      - FOWNER
      - SYS_CHROOT
    restart: on-failure:5
  
  mongo-seed:
    image: reminisceme/reverse-geoloc:latest
    volumes_from:
      - data
